---
title: "Sleep Study - Amy Bohnert - 2/27/2025"
format: pdf
editor: visual
---



```{r}
#Description of the models is here:
#https://docs.google.com/document/d/1wPBOgAGN5HowoabC0F4LSJFSpuju6Igh/edit

#Understanding geoids
#https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html

library(foreign)
library(tidyverse)
library(lattice)
library(lcsm)
library(ggplot2)
library(tidyr)
library(dplyr)
library(stringr)
library(lmerTest)
library(sjstats)
library(MuMIn)

#ID 2561 was on two rows.  It seems very clear that this should only have been one row.  
dat <- read.csv("../bohnert_sleep/CL_OTR_COI_Data.csv")
dat2 <- read.csv("../bohnert_sleep/CL_OTR v1 Youth Baseline COI3 Actigraphy Demo.csv")
```

# Data Cleaning and EDA
 - Observation ID 2561 had two rows in the data set.  I removed one of these rows.  

```{r}
#EDA
#ID 2561 is a problem
#dat %>% group_by(ID) %>% summarize(n = n()) %>% arrange(-n)
dat %>% filter(ID == 2561) %>% select(RecordedDate, ID, age.v1, gender.v1)

#Remove ID's that are NA
dat <- dat %>% filter(!is.na(ID))

#ID 2561 has two rows
#Fixing this here: 
dat[dat$ID == 2561 &
      is.na(dat$age.v1), c("age.v1", "age_dichotomous", "gender.v1")] <- 
  dat[dat$ID == 2561 & !is.na(dat$age.v1), c("age.v1", "age_dichotomous", "gender.v1")]
dat <- dat[dat$ID != 2561 |
             (dat$ID == 2561 & !is.na(dat$RecordedDate)), ]

#Convert gender 1/2 to male/female
dat <- dat %>% mutate(
  gender.v1 = case_when(gender.v1 == 1 ~ "male", gender.v1 == 2 ~ "female"),
  pdsMF.v1 = case_when(pdsMF.v1 == 1 ~ "male", pdsMF.v1 == 2 ~ "female")
)


```


##  Summary stats


```{r}
dat %>% summarize(
  mean_age = mean(age.v1, na.rm = T),
  pct_female = mean(pdsMF.v1 == "female", na.rm = T),
  mean_income = mean(income.v1, na.rm = T)
)

#ggplots for age and income
ggplot(aes(x = age.v1), data = dat) + geom_bar() + theme_bw()
ggplot(aes(x = age.v1, fill = pdsMF.v1), data = dat %>% filter(pdsMF.v1 %in% c("male","female"))) + geom_bar() + theme_bw() + facet_grid( pdsMF.v1 ~ 1)

ggplot(aes(x = income.v1), data = dat) + geom_histogram() + theme_bw() + geom_vline(aes(xintercept = median(dat$income, na.rm = TRUE)), color = "red") + ggtitle("Red line = Median")

ggplot(aes(x = cg1.edu.deg.v1), data = dat) + geom_bar() + theme_bw()

dat <- dat %>% mutate(cg1_edu_grp = factor(
  case_when(
    cg1.edu.deg.v1 %in% c(1, 2, 3) ~ "<=HS",
    cg1.edu.deg.v1 %in% c(4, 5, 6) ~ "<=BS",
    cg1.edu.deg.v1 %in% c(7, 8) ~ ">=MS"
  )
))

dat <- dat %>% mutate(cg1_edu_grp = fct_relevel(cg1_edu_grp, c("<=HS", "<=BS", ">=MS")))
ggplot(aes(x = cg1_edu_grp), data = dat) + geom_bar() + theme_bw()

ggplot(aes(x = cg1_edu_grp, fill = pdsMF.v1), data = dat %>% filter(pdsMF.v1 %in% c("male","female"))) + geom_bar() + theme_bw() + facet_grid( pdsMF.v1 ~ 1)

#need at least 5 days of actigraph data
table(dat$act_patotaldays)
#254+55+15 = 324

#I get 324
dat %>% filter(act_patotaldays >= 5 ) %>% nrow()

#Reproducing Table 1 stuff
dat %>% filter(act_patotaldays >= 5) %>% group_by(gender.v1) %>% summarize(age = mean(age.v1), n = n())

dat  %>% group_by(gender.v1) %>% summarize(
  age = mean(age.v1),
  n = n(),
  sleep = mean(act_totsleep.min_avg, na.rm = T),
  inbed = mean(act_totinbed.min_avg, na.rm = T),
  onset = mean(act_onset.time.min_d0, na.rm = T),
  eff = mean(act_efficiency_avg, na.rm = T)
)


#Average inbed time is a problem because times are circular
datinbed <- dat %>%
  select(ID, gender.v1, act_inbed.time_d0:act_inbed.time_d8) %>%
  pivot_longer(
    cols = starts_with("act_inbed.time_d"),
    names_prefix = "act_inbed.time_d",
    names_to = c("day"),
    values_to = "act_inbed_time"
  ) %>% mutate(act_inbed_time_numeric = as.numeric(do.call(rbind, strsplit(act_inbed_time, ":"))[, 1]) + as.numeric(do.call(rbind, strsplit(act_inbed_time, ":"))[, 2]) / 60,
               inbed.time_angle = 2*pi*act_inbed_time_numeric/24, 
               inbed.time_angle_x = cos(inbed.time_angle) ,
               inbed.time_angle_y = sin(inbed.time_angle),
               ) 

datweekend_yn <- dat %>%
  select(ID, act_weekday_yn_d0:act_weekday_yn_d8) %>%
  pivot_longer(
    cols = starts_with("act_weekday_yn_d"),
    names_to = c("day"),
    values_to = "act_weekday_yn",
    names_prefix = "act_weekday_yn_d",
  ) 

datinbed <- datinbed %>% left_join(datweekend_yn, by = c("ID","day"))

datinbedmean <- datinbed %>% group_by(gender.v1) %>% summarize(mean_x = mean(inbed.time_angle_x, na.rm = T),
mean_y = mean(inbed.time_angle_y, na.rm = T),n = n()) %>% mutate(mean_angle = atan(mean_y/mean_x),mean_time = mean_angle/(2*pi)*24, mean_x_uc = cos(mean_angle),  mean_y_uc = sin(mean_angle))

datinbedmean
ggplot(
  aes(
    x = inbed.time_angle_x,
    y = -inbed.time_angle_y,
    color = as.factor(gender.v1)
  ),
  data = datinbed %>% filter(gender.v1 %in% c("male", "female"))
) + geom_point(alpha = 0.05, size = 2) + coord_fixed() + facet_grid( ~ gender.v1) + geom_point(
  aes(x = mean_x_uc, y = -mean_y_uc),
  color = "red",
  data = datinbedmean %>% filter(gender.v1 %in% c("male", "female"))
) + geom_segment(x = 0,
                 y = 0,
                 xend = 1,
                 yend = 0) + geom_text(x = 0.5, y = 0.1, label = "0:00") + 
   geom_segment(x = 0,
                 y = 0,
                 xend = -1,
                 yend = 0) + geom_text(x = -0.5, y = 0.1, label = "12:00") + 
  geom_segment(x = 0,
               y = 0,
               xend = 0,
               yend = -1) + geom_text(x = 0.1, y = -0.5, label = "06:00", angle = -90) + 
  geom_segment(x = 0,
               y = 0,
               xend = 0,
               yend = 1) + geom_text(x = 0.1, y = 0.5, label = "18:00", angle = 90)



#Pivot longer
#DVs (sleep variables with models run for each sleep DV: 8 total):
# -act_totsleep.min
# -act.outbed.time
# -act.onset.time
# -act_efficiency
# -act_awakening.min
#Weekly level:
#Variability in:
  # -act_totsleep.min_sd
  # -act.outbed.time.min_sd
  # -act.onset.time_min.sd
##test
#Pivoting longer example:
# test <- dat %>%
#   select(ID, gender.v1, 
#          act_inbed.time_d0:act_inbed.time_d8,
#          act_weekday_yn_d0:act_weekday_yn_d8,
#          act_onset.time_d0: act_onset.time_d8) %>%
#   pivot_longer(
#     cols = -c(ID,gender.v1),
#     cols_vary = "slowest",
#     names_to = c(".value","day"),
#     names_pattern = "(.*)_d(.*)"
#   ) 
################
#Total Sleep
################z_ED_nat; z_HE_nat; z_SE_nat
datlong_resp <- dat %>%
  filter(act_patotaldays >= 5 & gender.v1 %in% c("male","female")) %>%
  select(
    ID,
    RecordedDate,
    pdsMF.v1,
    cg1.age.v1,
    income.v1,
    cg1_edu_grp,
    z_COI_nat,
    z_ED_nat,
    z_HE_nat,
    z_SE_nat,
    z_ED_EC_nat,
    z_ED_EL_nat,
    z_ED_ER_nat,
    z_ED_SP_nat,
    z_HE_EP_nat,
    z_HE_HE_nat,
    z_HE_HR_nat,
    z_HE_SE_nat,
    z_SE_EI_nat,
    z_SE_EO_nat,
    z_SE_ER_nat,
    z_SE_HQ_nat,
    z_SE_SR_nat,
    z_SE_WL_nat,
    act_totsleep.min_d0:act_totsleep.min_d8,
    act_outbed.time_d0:act_outbed.time_d8,
    act_onset.time_d0: act_onset.time_d8,
    act_efficiency_d0: act_efficiency_d8,
    act_weekday_yn_d0:act_weekday_yn_d8,
    act_awakening.min_d0: act_awakening.min_d8) %>%
  pivot_longer(
    cols = -c(ID,
              RecordedDate,
              pdsMF.v1,
              cg1.age.v1,
              income.v1,
              cg1_edu_grp,
              z_COI_nat,
              z_ED_nat,
              z_HE_nat,
              z_SE_nat,
             z_ED_EC_nat,
    z_ED_EL_nat,
    z_ED_ER_nat,
    z_ED_SP_nat,
    z_HE_EP_nat,
    z_HE_HE_nat,
    z_HE_HR_nat,
    z_HE_SE_nat,
    z_SE_EI_nat,
    z_SE_EO_nat,
    z_SE_ER_nat,
    z_SE_HQ_nat,
    z_SE_SR_nat,
    z_SE_WL_nat),
    cols_vary = "slowest",
    names_to = c(".value","day"),
    names_pattern = "(.*)_d(.*)"
  )


datlong_weekday_yn <- dat %>% 
  filter(act_patotaldays >=5 & gender.v1 %in% c("male","female") ) %>% 
  select(ID, pdsMF.v1, cg1.age.v1,income.v1,cg1.edu.deg.v1, act_weekday_yn_d0:act_weekday_yn_d8) %>% 
  pivot_longer(cols = starts_with("act_weekday_yn_d"), names_prefix = "act_weekday_yn_d",names_to = c("day"), values_to = "weekday_yn") 


#Weekend indicator should be Fri/Sat instead of a weekend (Sat/Sun) indicator
datlong <- datlong_resp %>% left_join(datlong_weekday_yn %>% select(ID,day,weekday_yn), by = c("ID","day"))
datlong <- datlong %>% group_by(ID) %>% mutate(I_frisat =  1 - lead(weekday_yn))
datlong <- datlong %>% group_by(ID) %>% mutate(I_frisat = ifelse(is.na(I_frisat),lag(I_frisat,7),I_frisat))
#datlong$Date <- do.call(rbind,strsplit(datlong$RecordedDate," "))[,1]
#datlong$Date <- mdy(datlong$Date)
#datlong$dayofweek <- wday(datlong$Date)

```

```{r}


#Fix time formating
#I cut off the day at 3pm. We could choose a different cut off
datlong <- datlong %>% ungroup() %>% mutate(
act_outbed.time_numeric = as.numeric(do.call(rbind,strsplit(datlong$act_outbed.time,":"))[,1]) + as.numeric(do.call(rbind,strsplit(datlong$act_outbed.time,":"))[,2])/60,
act_onset.time_numeric = as.numeric(do.call(rbind,strsplit(datlong$act_onset.time,":"))[,1]) + as.numeric(do.call(rbind,strsplit(datlong$act_onset.time,":"))[,2])/60) %>% 
  mutate(act_onset.time_numeric = ifelse(act_onset.time_numeric >= 17,act_onset.time_numeric-24,act_onset.time_numeric))

datlong <- datlong %>% mutate(income.v1.10000 = income.v1 / 10000)

datlong %>% group_by(I_frisat, pdsMF.v1) %>% 
  summarize(onset_mean = mean(act_onset.time_numeric, na.rm = T),
            outbed_mean = mean(act_outbed.time_numeric, na.rm = T))

ggplot(aes(x = act_onset.time_numeric,
           y = act_outbed.time_numeric,
           color = pdsMF.v1), data = datlong) + geom_point() + theme_bw() + facet_grid(~I_frisat)

ggplot(aes(y = act_onset.time_numeric,
           color = as.factor(I_frisat)), data = datlong) + geom_boxplot() + theme_bw() + facet_grid(~pdsMF.v1)

ggplot(aes(y = act_outbed.time_numeric,
           color = as.factor(I_frisat)), data = datlong) + geom_boxplot() + theme_bw() + facet_grid(~pdsMF.v1)
```

# Models 
## Total Sleep

```{r}
ggplot(aes(x = day, y = act_totsleep.min, group = ID, color = pdsMF.v1), data = datlong %>% filter(pdsMF.v1 %in% c("male","female"))) + geom_line(alpha = 0.05)  + theme_bw() + facet_grid(~pdsMF.v1)
```

```{r}
library(lme4)
################################
#act_totalsleep.min
################################
################################
#Model 1: COI Total
################################
mod1_totsleep <- lmer(act_totsleep.min ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp + I_frisat + z_COI_nat + (1|ID)  , data = datlong)
summary(mod1_totsleep)
ci <- confint(mod1_totsleep)
print(ci)

plot(mod1_totsleep, type=c("p","smooth"), col.line=1)

plot(mod1_totsleep,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod1_totsleep)

#Table
#Fixed effects
mod1_totsleep_table <- data.frame(
  predictor = attr(summary(mod1_totsleep)$coef,"dimnames")[[1]],
  B = summary(mod1_totsleep)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod1_totsleep)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod1_totsleep)$CI_low,4),", ",round(effectsize::standardize_parameters(mod1_totsleep)$CI_high,4),")"), 
pval = summary(mod1_totsleep)$coef[,5]
)

mod1_totsleep_table[,c("B","beta","pval")] <- 
round(mod1_totsleep_table[,c("B","beta","pval")],4)
write.csv(mod1_totsleep_table,file = "../bohnert_sleep_git/mod1_totsleep_table.csv")

#Random effects
#within
sigma2 <- summary(mod1_totsleep)$sigma^2
#between
tau00 <- attr(summary(mod1_totsleep)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod1_totsleep)$devcomp$dims["q"]
obs <- summary(mod1_totsleep)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod1_totsleep)[,"R2m"]
R2cond <- r.squaredGLMM(mod1_totsleep)[,"R2c"]
mod1_totsleep_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod1_totsleep_table_re
################################
#Model 2: COI Sub-domains
################################
mod2_totsleep <- lmer(act_totsleep.min ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp +  I_frisat + z_ED_nat +  z_HE_nat + z_SE_nat + (1|ID)  , data = datlong)
summary(mod2_totsleep)
ci <- confint(mod2_totsleep)


plot(mod2_totsleep, type=c("p","smooth"), col.line=1)

plot(mod2_totsleep,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod2_totsleep)

mod2_totsleep_table <- data.frame(
  predictor = attr(summary(mod2_totsleep)$coef,"dimnames")[[1]],
  B = summary(mod2_totsleep)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod2_totsleep)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod2_totsleep)$CI_low,4),", ",round(effectsize::standardize_parameters(mod2_totsleep)$CI_high,4),")"), 
pval = summary(mod2_totsleep)$coef[,5]
)

mod2_totsleep_table[,c("B","beta","pval")] <- 
round(mod2_totsleep_table[,c("B","beta","pval")],4)
write.csv(mod2_totsleep_table,file = "../bohnert_sleep_git/mod2_totsleep_table.csv")

#Random effects
#within
sigma2 <- summary(mod2_totsleep)$sigma^2
#between
tau00 <- attr(summary(mod2_totsleep)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod2_totsleep)$devcomp$dims["q"]
obs <- summary(mod2_totsleep)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod2_totsleep)[,"R2m"]
R2cond <- r.squaredGLMM(mod2_totsleep)[,"R2c"]
mod2_totsleep_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod2_totsleep_table_re
################################
#Model 3: COI Sub-domains
################################
mod3_totsleep <- lmer(act_totsleep.min ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp + z_ED_EC_nat + 
    z_ED_EL_nat + 
    z_ED_ER_nat + 
    z_ED_SP_nat + 
    z_HE_EP_nat + 
    z_HE_HE_nat + 
    z_HE_HR_nat + 
    z_HE_SE_nat + 
    z_SE_EI_nat + 
    z_SE_EO_nat + 
    z_SE_ER_nat + 
    z_SE_HQ_nat + 
    z_SE_SR_nat + 
    z_SE_WL_nat +  + (1|ID)  , data = datlong)
summary(mod3_totsleep)
ci <- confint(mod3_totsleep)
plot(mod3_totsleep, type=c("p","smooth"), col.line=1)

plot(mod3_totsleep,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod3_totsleep)

#Table
#Fixed Effects
mod3_totsleep_table <- data.frame(
  predictor = attr(summary(mod3_totsleep)$coef,"dimnames")[[1]],
  B = summary(mod3_totsleep)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod3_totsleep)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod3_totsleep)$CI_low,4),", ",round(effectsize::standardize_parameters(mod3_totsleep)$CI_high,4),")"), 
pval = summary(mod3_totsleep)$coef[,5]
)

mod3_totsleep_table[,c("B","beta","pval")] <- 
round(mod3_totsleep_table[,c("B","beta","pval")],4)
write.csv(mod3_totsleep_table,file = "../bohnert_sleep_git/mod3_totsleep_table.csv")

#Random effects
#within
sigma2 <- summary(mod3_totsleep)$sigma^2
#between
tau00 <- attr(summary(mod3_totsleep)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod3_totsleep)$devcomp$dims["q"]
obs <- summary(mod3_totsleep)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod3_totsleep)[,"R2m"]
R2cond <- r.squaredGLMM(mod3_totsleep)[,"R2c"]
mod3_totsleep_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod3_totsleep_table_re
```




## Sleep Efficiency

```{r}
ggplot(aes(x = day, y = act_efficiency, group = ID, color = pdsMF.v1), data = datlong %>% filter(pdsMF.v1 %in% c("male","female"))) + geom_line(alpha = 0.05)  + theme_bw() + facet_grid(~pdsMF.v1)
```

```{r}
library(lme4)
################################
#act_efficiency
################################
################################
#Model 1: COI Total
################################
mod1_eff <- lmer(act_efficiency ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp + I_frisat + z_COI_nat + (1|ID)  , data = datlong)
summary(mod1_eff)
ci <- confint(mod1_eff)
ci
plot(mod1_eff, type=c("p","smooth"), col.line=1)

plot(mod1_eff,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod1_eff)

#Table 
#fixed effects
mod1_eff_table <- data.frame(
  predictor = attr(summary(mod1_eff)$coef,"dimnames")[[1]],
  B = summary(mod1_eff)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod1_eff)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod1_eff)$CI_low,4),", ",round(effectsize::standardize_parameters(mod1_eff)$CI_high,4),")"), 
pval = summary(mod1_eff)$coef[,5]
)

mod1_eff_table[,c("B","beta","pval")] <- 
round(mod1_eff_table[,c("B","beta","pval")],4)
write.csv(mod1_eff_table,file = "../bohnert_sleep_git/mod1_eff_table.csv")

#Random effects
#within
sigma2 <- summary(mod1_eff)$sigma^2
#between
tau00 <- attr(summary(mod1_eff)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod1_eff)$devcomp$dims["q"]
obs <- summary(mod1_eff)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod1_eff)[,"R2m"]
R2cond <- r.squaredGLMM(mod1_eff)[,"R2c"]
mod1_eff_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod1_eff_table_re


################################
#Model 2: COI Sub-domains
################################
mod2_eff <- lmer(act_efficiency ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp +  I_frisat + z_ED_nat +  z_HE_nat + z_SE_nat + (1|ID)  , data = datlong)
summary(mod2_eff)
ci <- confint(mod2_eff)
ci

plot(mod2_eff, type=c("p","smooth"), col.line=1)

plot(mod2_eff,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod2_eff)

#Table 
#fixed effects
mod2_eff_table <- data.frame(
  predictor = attr(summary(mod2_eff)$coef,"dimnames")[[1]],
  B = summary(mod2_eff)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod2_eff)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod2_eff)$CI_low,4),", ",round(effectsize::standardize_parameters(mod2_eff)$CI_high,4),")"), 
pval = summary(mod2_eff)$coef[,5]
)

mod2_eff_table[,c("B","beta","pval")] <- 
round(mod2_eff_table[,c("B","beta","pval")],4)
write.csv(mod2_eff_table,file = "../bohnert_sleep_git/mod2_eff_table.csv")

#Random effects
#within
sigma2 <- summary(mod2_eff)$sigma^2
#between
tau00 <- attr(summary(mod2_eff)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod2_eff)$devcomp$dims["q"]
obs <- summary(mod2_eff)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod2_eff)[,"R2m"]
R2cond <- r.squaredGLMM(mod2_eff)[,"R2c"]
mod2_eff_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod2_eff_table_re
################################
#Model 3: COI Sub-domains
################################
mod3_eff <- lmer(act_efficiency ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp + z_ED_EC_nat + 
    z_ED_EL_nat + 
    z_ED_ER_nat + 
    z_ED_SP_nat + 
    z_HE_EP_nat + 
    z_HE_HE_nat + 
    z_HE_HR_nat + 
    z_HE_SE_nat + 
    z_SE_EI_nat + 
    z_SE_EO_nat + 
    z_SE_ER_nat + 
    z_SE_HQ_nat + 
    z_SE_SR_nat + 
    z_SE_WL_nat + (1|ID)  , data = datlong)
summary(mod3_eff)
ci <- confint(mod3_eff)
ci 
plot(mod3_eff, type=c("p","smooth"), col.line=1)

plot(mod3_eff,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod3_eff)

#Table 
#fixed effects
mod3_eff_table <- data.frame(
  predictor = attr(summary(mod3_eff)$coef,"dimnames")[[1]],
  B = summary(mod3_eff)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod3_eff)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod3_eff)$CI_low,4),", ",round(effectsize::standardize_parameters(mod3_eff)$CI_high,4),")"), 
pval = summary(mod3_eff)$coef[,5]
)

mod3_eff_table[,c("B","beta","pval")] <- 
round(mod3_eff_table[,c("B","beta","pval")],4)
write.csv(mod3_eff_table,file = "../bohnert_sleep_git/mod3_eff_table.csv")

#Random effects
#within
sigma2 <- summary(mod3_eff)$sigma^2
#between
tau00 <- attr(summary(mod3_eff)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod3_eff)$devcomp$dims["q"]
obs <- summary(mod3_eff)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod3_eff)[,"R2m"]
R2cond <- r.squaredGLMM(mod3_eff)[,"R2c"]
mod3_eff_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod3_eff_table_re
```


## Awakening

```{r}
ggplot(aes(x = day, y = act_awakening.min, group = ID, color = pdsMF.v1), data = datlong %>% filter(pdsMF.v1 %in% c("male","female"))) + geom_line(alpha = 0.05)  + theme_bw() + facet_grid(~pdsMF.v1)
```

```{r}
library(lme4)
################################
#act_awakening.min
################################
################################
#Model 1: COI Total
################################
mod1_awake <- lmer(act_awakening.min ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp + I_frisat + z_COI_nat + (1|ID)  , data = datlong)
summary(mod1_awake)
ci <- confint(mod1_awake)
ci

plot(mod1_awake, type=c("p","smooth"), col.line=1)

plot(mod1_awake,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod1_awake)

#Table
#Fixed effects
mod1_awake_table <- data.frame(
  predictor = attr(summary(mod1_awake)$coef,"dimnames")[[1]],
  B = summary(mod1_awake)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod1_awake)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod1_awake)$CI_low,4),", ",round(effectsize::standardize_parameters(mod1_awake)$CI_high,4),")"), 
pval = summary(mod1_awake)$coef[,5]
)

mod1_awake_table[,c("B","beta","pval")] <- 
round(mod1_awake_table[,c("B","beta","pval")],4)
write.csv(mod1_awake_table,file = "../bohnert_sleep_git/mod1_awake_table.csv")

#Random awakeects
#within
sigma2 <- summary(mod1_awake)$sigma^2
#between
tau00 <- attr(summary(mod1_awake)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod1_awake)$devcomp$dims["q"]
obs <- summary(mod1_awake)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod1_awake)[,"R2m"]
R2cond <- r.squaredGLMM(mod1_awake)[,"R2c"]
mod1_awake_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod1_awake_table_re

################################
#Model 2: COI Sub-domains
################################
mod2_awake <- lmer(act_awakening.min ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp +  I_frisat + z_ED_nat +  z_HE_nat + z_SE_nat + (1|ID)  , data = datlong)
summary(mod2_awake)
ci <- confint(mod2_awake)
ci

plot(mod2_awake, type=c("p","smooth"), col.line=1)

plot(mod2_awake,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod2_awake)

#Table
#Fixed effects
mod2_awake_table <- data.frame(
  predictor = attr(summary(mod2_awake)$coef,"dimnames")[[1]],
  B = summary(mod2_awake)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod2_awake)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod2_awake)$CI_low,4),", ",round(effectsize::standardize_parameters(mod2_awake)$CI_high,4),")"), 
pval = summary(mod2_awake)$coef[,5]
)

mod2_awake_table[,c("B","beta","pval")] <- 
round(mod2_awake_table[,c("B","beta","pval")],4)
write.csv(mod2_awake_table,file = "../bohnert_sleep_git/mod2_awake_table.csv")

#Random awakeects
#within
sigma2 <- summary(mod2_awake)$sigma^2
#between
tau00 <- attr(summary(mod2_awake)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod2_awake)$devcomp$dims["q"]
obs <- summary(mod2_awake)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod2_awake)[,"R2m"]
R2cond <- r.squaredGLMM(mod2_awake)[,"R2c"]
mod2_awake_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod2_awake_table_re


################################
#Model 3: COI Sub-domains
################################
mod3_awake <- lmer(act_awakening.min ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp + z_ED_EC_nat + 
    z_ED_EL_nat + 
    z_ED_ER_nat + 
    z_ED_SP_nat + 
    z_HE_EP_nat + 
    z_HE_HE_nat + 
    z_HE_HR_nat + 
    z_HE_SE_nat + 
    z_SE_EI_nat + 
    z_SE_EO_nat + 
    z_SE_ER_nat + 
    z_SE_HQ_nat + 
    z_SE_SR_nat + 
    z_SE_WL_nat + (1|ID)  , data = datlong)
summary(mod3_awake)
ci <- confint(mod3_awake)
ci 

plot(mod3_awake, type=c("p","smooth"), col.line=1)

plot(mod3_awake,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod3_awake)

#Table
#Fixed effects
mod3_awake_table <- data.frame(
  predictor = attr(summary(mod3_awake)$coef,"dimnames")[[1]],
  B = summary(mod3_awake)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod3_awake)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod3_awake)$CI_low,4),", ",round(effectsize::standardize_parameters(mod3_awake)$CI_high,4),")"), 
pval = summary(mod3_awake)$coef[,5]
)

mod3_awake_table[,c("B","beta","pval")] <- 
round(mod3_awake_table[,c("B","beta","pval")],4)
write.csv(mod3_awake_table,file = "../bohnert_sleep_git/mod3_awake_table.csv")

#Random awakeects
#within
sigma2 <- summary(mod3_awake)$sigma^2
#between
tau00 <- attr(summary(mod3_awake)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod3_awake)$devcomp$dims["q"]
obs <- summary(mod3_awake)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod3_awake)[,"R2m"]
R2cond <- r.squaredGLMM(mod3_awake)[,"R2c"]
mod3_awake_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod3_awake_table_re
```

## Sleep Onset 
```{r}
ggplot(aes(x = day, y = act_onset.time_numeric, group = ID, color = pdsMF.v1), data = datlong %>% filter(pdsMF.v1 %in% c("male","female"))) + geom_line(alpha = 0.05)  + theme_bw() + facet_grid(~pdsMF.v1)
```

```{r}
library(lme4)
################################
#act_onset.time_numeric
################################
################################
#Model 1: COI Total
################################
mod1_onset <- lmer(act_onset.time_numeric ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp + I_frisat + z_COI_nat + (1|ID)  , data = datlong)
summary(mod1_onset)
ci <- confint(mod1_onset)
ci

plot(mod1_onset, type=c("p","smooth"), col.line=1)

plot(mod1_onset,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod1_onset)


#Table
#Fixed effects
mod1_onset_table <- data.frame(
  predictor = attr(summary(mod1_onset)$coef,"dimnames")[[1]],
  B = summary(mod1_onset)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod1_onset)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod1_onset)$CI_low,4),", ",round(effectsize::standardize_parameters(mod1_onset)$CI_high,4),")"), 
pval = summary(mod1_onset)$coef[,5]
)

mod1_onset_table[,c("B","beta","pval")] <- 
round(mod1_onset_table[,c("B","beta","pval")],4)
write.csv(mod1_onset_table,file = "../bohnert_sleep_git/mod1_onset_table.csv")

#Random effects
#within
sigma2 <- summary(mod1_onset)$sigma^2
#between
tau00 <- attr(summary(mod1_onset)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod1_onset)$devcomp$dims["q"]
obs <- summary(mod1_onset)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod1_onset)[,"R2m"]
R2cond <- r.squaredGLMM(mod1_onset)[,"R2c"]
mod1_onset_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod1_onset_table_re

################################
#Model 2: COI Sub-domains
################################
mod2_onset <- lmer(act_onset.time_numeric ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp +  I_frisat + z_ED_nat +  z_HE_nat + z_SE_nat + (1|ID)  , data = datlong)
summary(mod2_onset)
ci <- confint(mod2_onset)
ci 

plot(mod2_onset, type=c("p","smooth"), col.line=1)

plot(mod2_onset,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod2_onset)

#Table
#Fixed effects
mod2_onset_table <- data.frame(
  predictor = attr(summary(mod2_onset)$coef,"dimnames")[[1]],
  B = summary(mod2_onset)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod2_onset)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod2_onset)$CI_low,4),", ",round(effectsize::standardize_parameters(mod2_onset)$CI_high,4),")"), 
pval = summary(mod2_onset)$coef[,5]
)

mod2_onset_table[,c("B","beta","pval")] <- 
round(mod2_onset_table[,c("B","beta","pval")],4)
write.csv(mod2_onset_table,file = "../bohnert_sleep_git/mod2_onset_table.csv")

#Random effects
#within
sigma2 <- summary(mod2_onset)$sigma^2
#between
tau00 <- attr(summary(mod2_onset)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod2_onset)$devcomp$dims["q"]
obs <- summary(mod2_onset)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod2_onset)[,"R2m"]
R2cond <- r.squaredGLMM(mod2_onset)[,"R2c"]
mod2_onset_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod2_onset_table_re
################################
#Model 3: COI Sub-domains
################################
mod3_onset <- lmer(act_onset.time_numeric ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp + z_ED_EC_nat + 
    z_ED_EL_nat + 
    z_ED_ER_nat + 
    z_ED_SP_nat + 
    z_HE_EP_nat + 
    z_HE_HE_nat + 
    z_HE_HR_nat + 
    z_HE_SE_nat + 
    z_SE_EI_nat + 
    z_SE_EO_nat + 
    z_SE_ER_nat + 
    z_SE_HQ_nat + 
    z_SE_SR_nat + 
    z_SE_WL_nat + (1|ID)  , data = datlong)
summary(mod3_onset)
ci <- confint(mod3_onset)
ci
plot(mod3_onset, type=c("p","smooth"), col.line=1)

plot(mod3_onset,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod3_onset)

#Table
#fixed effects
mod3_onset_table <- data.frame(
  predictor = attr(summary(mod3_onset)$coef,"dimnames")[[1]],
  B = summary(mod3_onset)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod3_onset)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod3_onset)$CI_low,4),", ",round(effectsize::standardize_parameters(mod3_onset)$CI_high,4),")"), 
pval = summary(mod3_onset)$coef[,5]
)

mod3_onset_table[,c("B","beta","pval")] <- 
round(mod3_onset_table[,c("B","beta","pval")],4)
write.csv(mod3_onset_table,file = "../bohnert_sleep_git/mod3_onset_table.csv")

#Random effects
#within
sigma2 <- summary(mod3_onset)$sigma^2
#between
tau00 <- attr(summary(mod3_onset)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod3_onset)$devcomp$dims["q"]
obs <- summary(mod3_onset)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod3_onset)[,"R2m"]
R2cond <- r.squaredGLMM(mod3_onset)[,"R2c"]
mod3_onset_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod3_onset_table_re
```

## Sleep Outbed

```{r}
ggplot(aes(x = day, y = act_outbed.time_numeric, group = ID, color = pdsMF.v1), data = datlong %>% filter(pdsMF.v1 %in% c("male","female"))) + geom_line(alpha = 0.05)  + theme_bw() + facet_grid(~pdsMF.v1)
```

```{r}
library(lme4)
################################
#act_outbed.time_numeric
################################
################################
#Model 1: COI Total
################################
mod1_outbed <- lmer(act_outbed.time_numeric ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp + I_frisat + z_COI_nat + (1|ID)  , data = datlong)
summary(mod1_outbed)
ci <- confint(mod1_outbed)
ci 

plot(mod1_outbed, type=c("p","smooth"), col.line=1)

plot(mod1_outbed,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod1_outbed)

mod1_outbed_table <- data.frame(
  predictor = attr(summary(mod1_outbed)$coef,"dimnames")[[1]],
  B = summary(mod1_outbed)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod1_outbed)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod1_outbed)$CI_low,4),", ",round(effectsize::standardize_parameters(mod1_outbed)$CI_high,4),")"), 
pval = summary(mod1_outbed)$coef[,5]
)

mod1_outbed_table[,c("B","beta","pval")] <- 
round(mod1_outbed_table[,c("B","beta","pval")],4)
write.csv(mod1_outbed_table,file = "../bohnert_sleep_git/mod1_outbed_table.csv")

#Random effects
#within
sigma2 <- summary(mod1_outbed)$sigma^2
#between
tau00 <- attr(summary(mod1_outbed)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod1_outbed)$devcomp$dims["q"]
obs <- summary(mod1_outbed)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod1_outbed)[,"R2m"]
R2cond <- r.squaredGLMM(mod1_outbed)[,"R2c"]
mod1_outbed_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod1_outbed_table_re


################################
#Model 2: COI Sub-domains
################################
mod2_outbed <- lmer(act_outbed.time_numeric ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp +  I_frisat + z_ED_nat +  z_HE_nat + z_SE_nat + (1|ID)  , data = datlong)
summary(mod2_outbed)
ci <- confint(mod2_outbed)
ci

plot(mod2_outbed, type=c("p","smooth"), col.line=1)

plot(mod2_outbed,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod2_outbed)


mod2_outbed_table <- data.frame(
  predictor = attr(summary(mod2_outbed)$coef,"dimnames")[[1]],
  B = summary(mod2_outbed)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod2_outbed)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod2_outbed)$CI_low,4),", ",round(effectsize::standardize_parameters(mod2_outbed)$CI_high,4),")"), 
pval = summary(mod2_outbed)$coef[,5]
)

mod2_outbed_table[,c("B","beta","pval")] <- 
round(mod2_outbed_table[,c("B","beta","pval")],4)
write.csv(mod2_outbed_table,file = "../bohnert_sleep_git/mod2_outbed_table.csv")

#Random effects
#within
sigma2 <- summary(mod2_outbed)$sigma^2
#between
tau00 <- attr(summary(mod2_outbed)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod2_outbed)$devcomp$dims["q"]
obs <- summary(mod2_outbed)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod2_outbed)[,"R2m"]
R2cond <- r.squaredGLMM(mod2_outbed)[,"R2c"]
mod2_outbed_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod2_outbed_table_re
################################
#Model 3: COI Sub-domains
################################
mod3_outbed <- lmer(act_outbed.time_numeric ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp + z_ED_EC_nat + 
    z_ED_EL_nat + 
    z_ED_ER_nat + 
    z_ED_SP_nat + 
    z_HE_EP_nat + 
    z_HE_HE_nat + 
    z_HE_HR_nat + 
    z_HE_SE_nat + 
    z_SE_EI_nat + 
    z_SE_EO_nat + 
    z_SE_ER_nat + 
    z_SE_HQ_nat + 
    z_SE_SR_nat + 
    z_SE_WL_nat + (1|ID)  , data = datlong)
summary(mod3_outbed)
confint(mod3_outbed)
plot(mod3_outbed, type=c("p","smooth"), col.line=1)

plot(mod3_outbed,
     sqrt(abs(resid(.)))~fitted(.),
     type=c("p","smooth"), col.line=1)

lattice::qqmath(mod3_outbed)


mod3_outbed_table <- data.frame(
  predictor = attr(summary(mod3_outbed)$coef,"dimnames")[[1]],
  B = summary(mod3_outbed)$coef[,"Estimate"],
  beta = effectsize::standardize_parameters(mod3_outbed)$Std_Coefficient,
  CI = paste0("(",round(ci[-c(1,2),1],4),", ",round(ci[-c(1,2),2],4),")"),
CI_STD = paste0("(",round(effectsize::standardize_parameters(mod3_outbed)$CI_low,4),", ",round(effectsize::standardize_parameters(mod3_outbed)$CI_high,4),")"), 
pval = summary(mod3_outbed)$coef[,5]
)

mod3_outbed_table[,c("B","beta","pval")] <- 
round(mod3_outbed_table[,c("B","beta","pval")],4)
write.csv(mod3_outbed_table,file = "../bohnert_sleep_git/mod3_outbed_table.csv")

#Random effects
#within
sigma2 <- summary(mod3_outbed)$sigma^2
#between
tau00 <- attr(summary(mod3_outbed)$varcor$ID,"stddev")^2
ICC <- tau00/(tau00 + sigma2)
N <- summary(mod3_outbed)$devcomp$dims["q"]
obs <- summary(mod3_outbed)$devcomp$dims["n"]
R2marg <- r.squaredGLMM(mod3_outbed)[,"R2m"]
R2cond <- r.squaredGLMM(mod3_outbed)[,"R2c"]
mod3_outbed_table_re <- data.frame(sigma2, tau00, ICC, N, obs, R2marg, R2cond)
mod3_outbed_table_re

# ################################
# #Model 4: Neighborhood Parent Report
# ################################
# mod4_outbed <- lmer(act_outbed.time_numeric ~ pdsMF.v1 + cg1.age.v1 + income.v1.10000 + cg1_edu_grp +  + (1|ID)  , data = datlong)
# summary(mod4_outbed)
# confint(mod4_outbed)
# plot(mod4_outbed, type=c("p","smooth"), col.line=1)
# 
# plot(mod4_outbed,
#      sqrt(abs(resid(.)))~fitted(.),
#      type=c("p","smooth"), col.line=1)
# 
# lattice::qqmath(mod4_outbed)
save.image("../bohnert_sleep/bohnert_sleep_20250228.rda")
```


